#!/bin/sh -e

export PROGDIR=$(dirname "$(realpath "$0")")

init() {
    mkdir -p photos/full photos/hd photos/thumb css js
    cp "$PROGDIR/template/index.md" index.md
}

md() {
    sed -E -f "$PROGDIR/md.sed" "$@"
}

build() {
    make -f "$PROGDIR/Makefile" build -j8
}

orphans() {
    make -f "$PROGDIR/Makefile" orphans
}

missing() {
    make -f "$PROGDIR/Makefile" missing
}

command=$1; shift

"$command" "$@"
