#!/bin/sh -e

if head -1 "$1" | grep -q '^#'; then
    title=$(head -1 "$1" | sed 's/^..//')
fi

convert_links() {
    sed 's/\.md"/.html"/g'
}

add_home() {
    sed 's,</h1>,<a href="/" class="home">Home</a></h1>,'
}

add_size() {
    while read line; do
        for pattern in $(echo "$line" | grep -o 'src="[^"]*.jpg"'); do
            file=$(echo "$pattern" | awk -F'"' '{print $2}')
            attrs=$(identify "./$file" | awk '{print $3}' | sed 's/^/width="/;s/x/" height="/;s/$/"/')
            line=$(echo "$line" | sed "s,$pattern,$pattern $attrs,g")
        done

        echo "$line"
    done
}

if [ "$1" = index.md ]; then
    add_home() {
        cat
    }
fi

cat "$PROGDIR/head.html" | sed "s/<title>/<title>$title/"
"$PROGDIR/node_modules/.bin/marked" "$1" | convert_links | add_home | add_size
cat "$PROGDIR/foot.html"
