#!/bin/sh -e

if head -1 "$1" | grep -q '^#'; then
    title=$(head -1 "$1" | sed 's/^..//')
fi

convert_links() {
    sed 's/\.md"/.html"/g'
}

add_home() {
    sed 's,</h1>,<a href="/" class="home">Home</a></h1>,'
}

add_intrinsicsize() {
    content=$(cat)

    for pattern in $(echo "$content" | grep -o 'src="[^"]*.jpg"'); do
        file=$(echo "$pattern" | awk -F'"' '{print $2}')
        size=$(identify "./$file" | awk '{print $3}')
        content=$(echo "$content" | sed "s,$pattern,$pattern intrinsicsize=\"$size\",g")
    done

    echo "$content"
}

if [ "$1" = index.md ]; then
    add_home() {
        cat
    }
fi

cat "$PROGDIR/head.html" | sed "s/<title>/<title>$title/"
"$PROGDIR/node_modules/.bin/marked" "$1" | convert_links | add_home | add_intrinsicsize
cat "$PROGDIR/foot.html"
